name: flutter_java_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  pocketbase: ^0.12.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0 
  http: ^1.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
